### ISSUE TITLE
适配公众号编辑器

### ISSUE THREAD

**Issue by LENGSHIER** [ec50n9/135-evolution#1]
大佬是否可以把“编辑增强”功能也适配到公众号本体上，修改文章起来更方便，期待

**Comment by ec50n9** [comment]
非常欣喜地看到这个脚本的第一个改进建议，我认为这是一个很不错的功能，我将尽快适配，有新进展我会在这里回复你，感谢！

**Comment by ec50n9** [comment]
你好，脚本对公众号编辑器进行了适配，在脚本市场更新到2.0.1版本即可使用。
